### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by khm159** [zhang-can/PAN-PyTorch#3]
Could you please tell me about running environments?
python version, cuda version, pytorch version, and other things...

**Comment by zhang-can** [comment]
hi @khm159 ,

We use the following environments:
* python 3.6 (Anaconda3 5.1.0)
* cuda 10.0
* pytorch 1.0.0
* Ubuntu 16.04 LTS

**Comment by khm159** [comment]
Thank you for your answer. Have a nice day. 👍
