### ISSUE TITLE
What is the label start number?

### ISSUE THREAD

**Issue by khm159** [zhang-can/PAN-PyTorch#4]
Hello, zhang-can

Thanks for your code sharing. 
It was very helpful.

I have a question while using this code.
I inputed ucf 101 file like this... 

in UCF-101 dataset, ApplyEyeMakeup is first lable so i make training.txt like this.. 
v_ApplyEyeMakeup_g01_c01 163 1
Am I wrong??

Thank you for your reply in advance.

**Comment by zhang-can** [comment]
Hi @khm159 ,

Thanks for your interest in our work!
The label should start from 0, for UCF101, the label range should be 0-100 (total 101).

**Comment by khm159** [comment]
Thank you very much @zhang-can
